services:
  sapataria-vieira:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sapataria-vieira
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    restart: unless-stopped
